### ISSUE TITLE
Cache downloading not working anymore

### ISSUE THREAD

**Issue by Kazhuu** [webhamster/advancedcaching#188]
It seems currently I cannot load any caches from my phone anymore. My phone is Nokia N9 and I have downloaded latest version from this page: http://213.128.137.28/showthread.php?t=48036&page=41.

Last fix was made by AapoRantalainen. Currently I cannot download caches at all. When I start the application from command line I get his stacktrace:

Update requested.
 44958      ERROR cachedownloader      Wrong username or password! // cachedownloader.py:108
Traceback (most recent call last):
  File "/opt/advancedcaching/cachedownloader.py", line 106, in get_overview
    points = self._get_overview(location, get_geocache_callback, skip_callback = skip_callback)
  File "/opt/advancedcaching/cachedownloader.py", line 192, in _get_overview
    response = self.downloader.get_reader(url, login_callback = self.login_callback, check_login_callback = self.check_login_callback)
  File "/opt/advancedcaching/downloader.py", line 170, in get_reader
    self.login(login_callback, check_login_callback)
  File "/opt/advancedcaching/downloader.py", line 153, in login
    login_callback(self, self.username, self.password)
  File "/opt/advancedcaching/cachedownloader.py", line 353, in login_callback
    raise Exception("Wrong username or password!")
Exception: Wrong username or password!
 44973      ERROR root                 Wrong username or password! // core.py:944
Traceback (most recent call last):
  File "/opt/advancedcaching/cachedownloader.py", line 106, in get_overview
    points = self._get_overview(location, get_geocache_callback, skip_callback = skip_callback)
  File "/opt/advancedcaching/cachedownloader.py", line 192, in _get_overview
    response = self.downloader.get_reader(url, login_callback = self.login_callback, check_login_callback = self.check_login_callback)
  File "/opt/advancedcaching/downloader.py", line 170, in get_reader
    self.login(login_callback, check_login_callback)
  File "/opt/advancedcaching/downloader.py", line 153, in login
    login_callback(self, self.username, self.password)
  File "/opt/advancedcaching/cachedownloader.py", line 353, in login_callback
    raise Exception("Wrong username or password!")
Exception: Wrong username or password!
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
Update geocaches called

I even tried to do dummy account and still it doesn't work. Is the problem with geocaching.com changing their api or some token problem? And more importantly does anybody else has the same problem?

**Comment by aapo** [comment]
Unfortunately this is the situation. Geocaching.com has been changed and now agtl can't even do login.
